import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const locales = ['ru', 'de'] as const;
const sphereIds = ['events', 'photographer', 'travel', 'massage'] as const;
const outputPath = resolve('src/lib/kb-templates/templates.gen.ts');
const check = process.argv.includes('--check');

function buildOutput(): string {
  const templates = Object.fromEntries(
    locales.map((locale) => [
      locale,
      Object.fromEntries(
        sphereIds.map((sphereId) => {
          const path = resolve('src/lib/kb-templates', locale, `${sphereId}.md`);

          try {
            return [sphereId, readFileSync(path, 'utf8')];
          } catch (error) {
            const reason = error instanceof Error ? error.message : String(error);
            throw new Error(`Missing KB template for ${locale}/${sphereId}: ${reason}`);
          }
        }),
      ),
    ]),
  );

  return `// AUTO-GENERATED by scripts/gen-kb-templates.ts. Do not edit manually.\n\nexport const KB_TEMPLATES = ${JSON.stringify(templates, null, 2)} as const;\n`;
}

const output = buildOutput();

if (check) {
  let current = '';
  try {
    current = readFileSync(outputPath, 'utf8');
  } catch {
    // The mismatch message below covers an absent generated file as well.
  }

  if (current !== output) {
    throw new Error('KB templates are out of sync. Run pnpm gen:kb-templates.');
  }
} else {
  writeFileSync(outputPath, output, 'utf8');
}
